version: "3.8"

services:
  frontend:
    build:
      context: ./Duck.Web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./Duck.Web:/app:ro
    networks:
      - duck-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5115:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/Duck.db
    volumes:
      - sqlite-data:/app/data  # Här monterar jag volymen till /app/data
    networks:
      - duck-network

volumes:
  sqlite-data:  # Här definierar jag volymen som kommer att vara persistent
  
networks:
  duck-network:
    driver: bridge