# Byggandet
FROM node:20-alpine AS build

# Vart arbetskatalogen är
WORKDIR /app

# Kopierar package för att kunna installlera npm paketen
COPY package*.json ./

# Installerar beroenden (bättre med ci än install)
RUN npm ci

# Kopierar resten av applikationen
COPY . .

# Bygger applikationen
RUN npm run build

# ---- Prodsteg ----
FROM nginx:alpine AS production

# Kopierar de byggda filerna från builden vi gjorde precis innan
COPY --from=build /app/dist /usr/share/nginx/html

# Kopierar nginx-konfigurationen
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponerar port 80
EXPOSE 80

# Kommando för att starta nginx i förgrunden vilket är viktigt för Docker
CMD ["nginx", "-g", "daemon off;"]